# Regression and model validation

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.


### part1. Know the dataset
#### Read the students2014 data
> students2014 <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep=",", header=TRUE)

#### Explore the data structure and dimensions
> str(students2014)

#### Brief description to original dataset

> 
The resource data is collected from the student self evaluation survey from course **Introduction to Social Statistics, fall 2014 - in Finnish**. This survey is devided into A, B, C and D parts.
- Measures A and C are based on parts A and C in [ASSIST](http://www.etl.tla.ed.ac.uk/publications.html#measurement)
(Approaches and Study Skills Inventory for Students).
- Measures B (ASSIST B) are connected to the corresponding dimensions (Deep/SUrface/STrategic).
- Measure D is based on [SATS](http://www.evaluationandstatistics.com/) (Survey of Attitudes Toward Statistics).
- Compared to the original 52 item ASSIST we here used a brief version (created by Primi, Chiesi et al), including 32 items.

#### Brief description to student2014 dataset
> 
The student2014 dataset has 7 variables, including gender, age, attitute, deep, str, surf, and points, and 166 rows.
- gender: F (Female, 1), M (Male, 2)
- age: age in years
- attitude: Measure on the Likert scale (1-5)
- deep: Measures B for deep questions
- stra: Measures B for surface questions
- surf: Measures B for strategic questions
- points: Exam points excepted zero


### Part2. Graphical overview

#### Create an plot matrix with ggpairs()
> ggpairs(learning2014, lower = list(combo = wrap("facethist", bins = 20)))

#### Create a regression model with multiple explanatory variables
> my_model2 <- lm(points ~ attitude + stra + surf, data = learning2014)

- *hint: When there are more than one explanatory variables in the linear model, it is called multiple regression. In R, it is easy to include more than one explanatory variables in your linear model. This is done by simply defining more explanatory variables with the formula argument of lm(), as **y ~ x1 + x2 + ..** *

#### print out a summary of the model
> summary(my_model2)

#### Brief description to student2014 dataset graphical overview



